# Generated by Django 5.0.2 on 2024-02-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_seat_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='category',
        ),
    ]
